import { Header } from '@/components'
import { GlobalProvider } from '@/context/global/globalProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <GlobalProvider>
          <Header />
          <main className='min-h-[80vh] px-4 flex flex-col items-center justify-center'>{children}</main>
        </GlobalProvider>
      </body>
    </html>
  )
}
